---
- name: Deploy NSX-T Segment
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create NSX-T Segment
      nsxt_policy_segment:
        display_name: MySegment
        transport_zone_path: /infra/sites/default/enforcement-points/default/transport-zones/MyTZ
        subnets:
          - gateway_ip: 192.168.1.1
            prefix_length: 24
          - gateway_ip: 10.0.0.1
            prefix_length: 16
      delegate_to: localhost

    - name: Configure Firewall Rules
      nsxt_policy_security_policy:
        display_name: MySecurityPolicy
        rules:
          - name: Allow HTTP
            action: ALLOW
            sources:
              - segments:
                  - /infra/segments/MySegment
            destinations:
              - segments:
                  - /infra/segments/OtherSegment
            services:
              - /infra/services/HTTP
      delegate_to: localhost

#ansible-playbook nsxt_segment_playbook.yaml

#ansible-galaxy collection install git+https://github.com/vmware/ansible-for-nsxt


Write an Ansible role to Create an NSX-T segment with tasks to Add subnets to the segment, Configure firewall rules and policies.
